import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

const step1 = fs.readFileSync(new URL('../supabase/migrations/202608040001_award_groups.sql', import.meta.url), 'utf8');
const step2a = fs.readFileSync(new URL('../supabase/migrations/202608050002_rls_immutable_audit.sql', import.meta.url), 'utf8');
const step2b = fs.readFileSync(new URL('../supabase/migrations/202608050003_atomic_workflows.sql', import.meta.url), 'utf8');
const step3 = fs.readFileSync(new URL('../supabase/migrations/202608050004_quantity_units_balances.sql', import.meta.url), 'utf8');
const step4 = fs.readFileSync(new URL('../supabase/migrations/202608050005_xss_safe_excel.sql', import.meta.url), 'utf8');
const step5 = fs.readFileSync(new URL('../supabase/migrations/202608050006_fixed_rhodes_award_groups.sql', import.meta.url), 'utf8');
const saveStatusHotfix = fs.readFileSync(new URL('../supabase/migrations/202608050008_fix_save_request_status.sql', import.meta.url), 'utf8');
const atavyrosHotfix = fs.readFileSync(new URL('../supabase/migrations/202608060001_fix_atavyros_unit_name.sql', import.meta.url), 'utf8');
const groupsHotfix = fs.readFileSync(new URL('../supabase/migrations/202608060002_fix_south_rhodes_unit_name.sql', import.meta.url), 'utf8');
const groupsVerify = fs.readFileSync(new URL('../supabase/102_VERIFY_GROUPS_HOTFIX.sql', import.meta.url), 'utf8');

const ADMIN_ID = '00000000-0000-0000-0000-000000000001';
const UNIT2_ID = '00000000-0000-0000-0000-000000000002';
const OTHER_ADMIN_ID = '00000000-0000-0000-0000-000000000003';

const baseSchema = String.raw`
create role anon nologin;
create role authenticated nologin;
create schema auth;
create table auth.users (id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.municipal_units (
  id bigint primary key, name text not null, short_name text, sort_order integer
);
create table public.profiles (
  id uuid primary key references auth.users(id), role text not null,
  municipal_unit_id bigint references public.municipal_units(id),
  full_name text, email text
);
create table public.procurement_groups (
  id bigint primary key, code text, name text, short_name text,
  sort_order integer, domain text default 'procurement'
);
create table public.materials (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.procurement_groups(id),
  code text, name text not null, short_name text, subcategory text, unit text,
  cpv text, default_unit_price numeric, sort_order integer,
  technical_specs text, standards text, ce_required boolean default false,
  notes_for_tender text, is_active boolean default true,
  updated_at timestamptz default now()
);
create type public.request_status as enum ('draft', 'saved', 'cleaned', 'exported', 'locked');
create table public.unit_requests (
  id bigint generated by default as identity primary key,
  municipal_unit_id bigint not null references public.municipal_units(id),
  group_id bigint not null references public.procurement_groups(id),
  request_year integer not null, title text, status public.request_status default 'draft',
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz default now(), updated_at timestamptz default now(),
  saved_at timestamptz, cleaned_at timestamptz
);
create table public.request_lines (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.unit_requests(id),
  material_id bigint not null references public.materials(id),
  quantity numeric not null, unit_price numeric not null, comments text,
  updated_by uuid references auth.users(id), updated_at timestamptz default now(),
  unique(request_id, material_id)
);
create table public.saved_versions (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.unit_requests(id),
  action text not null, created_by uuid references auth.users(id),
  snapshot jsonb, created_at timestamptz default now()
);
create table public.locked_studies (
  id bigint generated by default as identity primary key,
  municipal_unit_id bigint not null references public.municipal_units(id),
  group_id bigint not null references public.procurement_groups(id),
  request_year integer not null, source_request_id bigint references public.unit_requests(id),
  seq integer not null, label text, net_total numeric not null,
  item_count integer not null, lines jsonb not null,
  supplier_name text, kimdis_url text, locked_by uuid references auth.users(id),
  locked_at timestamptz default now()
);
create table public.tender_overrides (
  id text primary key, data jsonb, updated_by uuid references auth.users(id),
  updated_at timestamptz default now()
);
create table public.mo_suppliers (
  id bigint generated by default as identity primary key,
  name text not null, afm text, email text, viber_phone text, phone text,
  address text, active boolean default true, created_at timestamptz default now()
);
create table public.mo_receivers (
  id bigint generated by default as identity primary key,
  name text not null, role text, email text, viber_phone text,
  active boolean default true, created_at timestamptz default now()
);
create table public.mo_contracts (
  id bigint generated by default as identity primary key,
  title text, cpv text, total_amount numeric, vat_rate numeric,
  active boolean default true, municipal_unit_id bigint references public.municipal_units(id),
  source_study_id bigint references public.locked_studies(id),
  supplier_id bigint references public.mo_suppliers(id), adam text, protocol_no text,
  start_date date, end_date date, created_at timestamptz default now()
);
create table public.mo_contract_items (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.mo_contracts(id),
  code text, description text, unit text, cpv text,
  contract_qty numeric, unit_price numeric, material_id bigint references public.materials(id),
  created_at timestamptz default now()
);
create table public.mo_orders (
  id bigint generated by default as identity primary key,
  order_no text, order_date date, supplier_id bigint references public.mo_suppliers(id),
  contract_id bigint references public.mo_contracts(id), receiver_id bigint references public.mo_receivers(id),
  project_id bigint, usage_location text, notes text, vat_rate numeric,
  subtotal numeric, vat numeric, total numeric, status text default 'draft',
  sent_at timestamptz, received_at timestamptz,
  municipal_unit_id bigint references public.municipal_units(id),
  study_id bigint references public.locked_studies(id),
  issued_at timestamptz, issued_by uuid references auth.users(id),
  created_by uuid references auth.users(id), created_at timestamptz default now()
);
create table public.mo_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.mo_orders(id),
  contract_item_id bigint references public.mo_contract_items(id),
  is_custom boolean default false, mapping jsonb,
  description text, unit text, quantity numeric, unit_price numeric, line_total numeric,
  created_at timestamptz default now()
);
`;

async function scalar(db, sql, params = []) {
  const result = await db.query(sql, params);
  const row = result.rows[0] || {};
  return row[Object.keys(row)[0]];
}

test('οι migrations v36.5.1 εφαρμόζουν τις τέσσερις σταθερές ομάδες, ποσότητες, υπόλοιπα, ατομικότητα και ασφαλή Excel', async () => {
  const db = new PGlite();
  try {
    await db.exec(baseSchema);
    await db.exec(`
      insert into public.municipal_units(id,name,short_name,sort_order) values
        (1,'Ρόδος','Ρόδου',1),
        (2,'Ιαλυσός','Ιαλυσού',2),
        (3,'Καλλιθέα','Καλλιθέας',3),
        (4,'Αφάντου','Αφάντου',4),
        (5,'Λίνδος','Λίνδου',5),
        (6,'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΝΟΤΙΑΣ ΡΟΔΟΥ','ΝΟΤΙΑΣ ΡΟΔΟΥ',6),
        (7,'Αρχάγγελος','Αρχαγγέλου',7),
        (8,'Πεταλούδες','Πεταλουδών',8),
        (9,'Κάμειρος','Καμείρου',9),
        (10,'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΤΑΒΥΡΟΥ','ΑΤΑΒΥΡΟΥ',10),
        (11,'Δήμος Ρόδου','Σύνολο',11);
      insert into auth.users(id,email) values
        ('${ADMIN_ID}','admin@example.test'),('${OTHER_ADMIN_ID}','other-admin@example.test');
      insert into public.profiles(id,role,municipal_unit_id,full_name,email)
        values
          ('${ADMIN_ID}','admin',null,'Διαχειριστής','admin@example.test'),
          ('${OTHER_ADMIN_ID}','admin',null,'Άλλος διαχειριστής','other-admin@example.test');
      insert into public.procurement_groups(id,code,name,short_name,sort_order,domain)
        values (10,'electrical','Ηλεκτρολογικό υλικό','Ηλεκτρολογικά',1,'procurement');
      insert into public.materials(group_id,code,name,short_name,unit,default_unit_price,sort_order)
        values (10,'M1','Υλικό 1','Υλικό 1','τεμ.',100,1),
               (10,'M2','Υλικό 2','Υλικό 2','τεμ.',100,2),
               (10,'M3','Καλώδιο σε μέτρα','Καλώδιο','m',10,3);
      insert into public.mo_contracts(title,source_study_id) values
        ('Ιστορική ανάθεση χωρίς σύνδεση 1',null),
        ('Ιστορική ανάθεση χωρίς σύνδεση 2',null);
      insert into public.mo_orders(order_no,order_date,status,municipal_unit_id)
        values ('ΔΥ-2026-01-007','2026-07-31','issued',1);
      select set_config('request.jwt.claim.sub','${ADMIN_ID}',false);
    `);

    await db.exec(step1);
    await db.exec(step2a);
    await db.exec(step2b);
    await db.exec(step3);
    await db.exec(step4);
    await db.exec(step5);

    assert.equal(await scalar(db, `select public.app_schema_version()`), '36.5.1');
    await db.exec(`
      create or replace function public.app_schema_version()
      returns text language sql stable security definer set search_path=public,pg_temp
      as $$ select '36.5.5'::text $$;
    `);
    await db.exec(saveStatusHotfix);
    await db.exec(saveStatusHotfix);
    await db.exec(`
      create or replace function public.app_rhodes_municipal_unit_code(p_name text,p_short_name text)
      returns text language plpgsql immutable parallel safe as $$
      declare v_key text := public.app_greek_key(coalesce(p_name,'') || ' ' || coalesce(p_short_name,''));
      begin
        if position('νοτιαροδο' in v_key)>0 then return 'south_rhodes'; end if;
        if position('ιαλυσο' in v_key)>0 then return 'ialysos'; end if;
        if position('καλλιθε' in v_key)>0 then return 'kallithea'; end if;
        if position('αφαντ' in v_key)>0 then return 'afantou'; end if;
        if position('λινδ' in v_key)>0 then return 'lindos'; end if;
        if position('αρχαγγελ' in v_key)>0 then return 'archangelos'; end if;
        if position('πεταλουδ' in v_key)>0 then return 'petaloudes'; end if;
        if position('καμειρ' in v_key)>0 then return 'kamiros'; end if;
        if position('ατταβυρ' in v_key)>0 then return 'attavyros'; end if;
        if position('ροδο' in v_key)>0 then return 'rhodes'; end if;
        return null;
      end $$;
    `);
    assert.equal(
      await scalar(db, `select public.app_rhodes_municipal_unit_code('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΤΑΒΥΡΟΥ','ΑΤΑΒΥΡΟΥ')`),
      null,
      'αναπαράγεται η αστοχία της ήδη εγκατεστημένης v36.5.5 πριν από το hotfix'
    );
    await db.exec(atavyrosHotfix);
    await db.exec(atavyrosHotfix);
    assert.equal(
      await scalar(db, `select public.app_rhodes_municipal_unit_code('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΝΟΤΙΑΣ ΡΟΔΟΥ','ΝΟΤΙΑΣ ΡΟΔΟΥ')`),
      'rhodes',
      'αναπαράγεται η σύγχυση της Νότιας Ρόδου με τη Δ.Ε. Ρόδου μετά το πρώτο hotfix'
    );
    await db.exec(groupsHotfix);
    await db.exec(groupsHotfix);
    assert.match(
      await scalar(db, `select pg_get_functiondef(
        'public.save_unit_request_atomic(text,bigint,bigint,integer,text,text,jsonb)'::regprocedure
      )`),
      /v_status public\.unit_requests\.status%type/,
      'το hotfix εγκαθίσταται επαναλήψιμα και διατηρεί το status στον enum τύπο της στήλης'
    );
    assert.equal(
      await scalar(db, `select public.app_rhodes_municipal_unit_code('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΤΑΒΥΡΟΥ','ΑΤΑΒΥΡΟΥ')`),
      'attavyros',
      'αναγνωρίζεται η ακριβής γραφή του εγκατεστημένου καταλόγου με ένα τ'
    );
    assert.equal(
      await scalar(db, `select public.app_rhodes_municipal_unit_code('Αττάβυρος','Ατταβύρου')`),
      'attavyros',
      'παραμένει συμβατή και η γραφή με δύο τ'
    );
    assert.equal(
      await scalar(db, `select public.app_rhodes_municipal_unit_code('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΝΟΤΙΑΣ ΡΟΔΟΥ','ΝΟΤΙΑΣ ΡΟΔΟΥ')`),
      'south_rhodes',
      'η πραγματική γραφή ΝΟΤΙΑΣ ΡΟΔΟΥ αναγνωρίζεται ως αυτοτελής Δ.Ε.'
    );
    assert.equal(
      Number(await scalar(db, `select public.app_rhodes_award_group_no('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΝΟΤΙΑΣ ΡΟΔΟΥ','ΝΟΤΙΑΣ ΡΟΔΟΥ')`)),
      3,
      'η Νότια Ρόδος εντάσσεται στην Ομάδα 3'
    );
    assert.equal(
      Number(await scalar(db, `select public.app_rhodes_award_group_no('ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΡΟΔΟΥ','ΡΟΔΟΥ')`)),
      1,
      'η Δ.Ε. Ρόδου παραμένει στην Ομάδα 1'
    );
    assert.deepEqual(
      (await db.query(`select group_no, count(*)::integer as unit_count from public.app_rhodes_award_group_template() group by group_no order by group_no`)).rows,
      [
        { group_no: 1, unit_count: 1 },
        { group_no: 2, unit_count: 3 },
        { group_no: 3, unit_count: 3 },
        { group_no: 4, unit_count: 3 }
      ],
      'και οι 10 πραγματικές Δ.Ε. κατανέμονται ακριβώς 1/3/3/3'
    );
    const verifyGroupsRow = (await db.query(groupsVerify)).rows[0];
    assert.deepEqual(
      {
        schema_version: verifyGroupsRow.schema_version,
        south_rhodes_genitive_code: verifyGroupsRow.south_rhodes_genitive_code,
        south_rhodes_group_no: Number(verifyGroupsRow.south_rhodes_group_no),
        rhodes_code: verifyGroupsRow.rhodes_code,
        rhodes_group_no: Number(verifyGroupsRow.rhodes_group_no),
        atavyros_single_t_code: verifyGroupsRow.atavyros_single_t_code,
        rhodes_template_units: Number(verifyGroupsRow.rhodes_template_units),
        distinct_unit_codes: Number(verifyGroupsRow.distinct_unit_codes),
        group_1_units: Number(verifyGroupsRow.group_1_units),
        group_2_units: Number(verifyGroupsRow.group_2_units),
        group_3_units: Number(verifyGroupsRow.group_3_units),
        group_4_units: Number(verifyGroupsRow.group_4_units)
      },
      {
        schema_version: '36.5.5',
        south_rhodes_genitive_code: 'south_rhodes',
        south_rhodes_group_no: 3,
        rhodes_code: 'rhodes',
        rhodes_group_no: 1,
        atavyros_single_t_code: 'attavyros',
        rhodes_template_units: 10,
        distinct_unit_codes: 10,
        group_1_units: 1,
        group_2_units: 3,
        group_3_units: 3,
        group_4_units: 3
      },
      'το αναγνωστικό 102_VERIFY_GROUPS_HOTFIX.sql επιστρέφει ακριβώς την αναμενόμενη κατανομή'
    );
    assert.equal(Number(await scalar(db, `select quantity_scale from public.materials where code='M1'`)), 0);
    assert.equal(Number(await scalar(db, `select quantity_scale from public.materials where code='M3'`)), 3);

    assert.equal(Number(await scalar(db, `
      select last_value from public.mo_order_number_counters
      where scope='mo-2026-u1-procurement'
    `)), 7, 'η αρίθμηση συνεχίζει από το ιστορικό δελτίων');

    const groupPayload = JSON.stringify([
      { group_no: 1, name: 'Ρόδου', municipal_unit_ids: [1] },
      { group_no: 2, name: 'Ιαλυσού – Καλλιθέας – Αφάντου', municipal_unit_ids: [2, 3, 4] },
      { group_no: 3, name: 'Λίνδου – Νότιας Ρόδου – Αρχαγγέλου', municipal_unit_ids: [5, 6, 7] },
      { group_no: 4, name: 'Πεταλουδών – Καμείρου – Ατταβύρου', municipal_unit_ids: [8, 9, 10] }
    ]);
    await db.exec(`delete from public.municipal_units where id=10`);
    await db.exec(`insert into public.municipal_units(id,name,short_name,sort_order) values (10,'Ιαλυσός αντί Ατταβύρου','Ιαλυσού',10)`);
    await assert.rejects(
      db.query(
        `select public.save_award_group_configuration($1,$2,$3,$4,$5,$6::jsonb)`,
        [2026, '100/2026', '2026-08-01', 'Ψ-TEST', 30000, groupPayload]
      ),
      /ακριβώς τις 10 Δημοτικές Ενότητες/i
    );
    await db.exec(`delete from public.municipal_units where id=10; insert into public.municipal_units(id,name,short_name,sort_order) values (10,'ΔΗΜΟΤΙΚΗ ΕΝΟΤΗΤΑ ΑΤΑΒΥΡΟΥ','ΑΤΑΒΥΡΟΥ',10)`);
    await assert.rejects(
      db.query(
        `select public.save_award_group_configuration($1,$2,$3,$4,$5,$6::jsonb)`,
        [2026, '100/2026', '2026-08-01', 'Ψ-TEST', 29999, groupPayload]
      ),
      /30\.000,00/
    );
    const wrongGroupPayload = JSON.stringify([
      { group_no: 1, name: 'Ρόδου', municipal_unit_ids: [2] },
      { group_no: 2, name: 'Ιαλυσού – Καλλιθέας – Αφάντου', municipal_unit_ids: [1, 3, 4] },
      { group_no: 3, name: 'Λίνδου – Νότιας Ρόδου – Αρχαγγέλου', municipal_unit_ids: [5, 6, 7] },
      { group_no: 4, name: 'Πεταλουδών – Καμείρου – Ατταβύρου', municipal_unit_ids: [8, 9, 10] }
    ]);
    await assert.rejects(
      db.query(
        `select public.save_award_group_configuration($1,$2,$3,$4,$5,$6::jsonb)`,
        [2026, '100/2026', '2026-08-01', 'Ψ-TEST', 30000, wrongGroupPayload]
      ),
      /ανήκει υποχρεωτικά στην ομάδα/i
    );
    await db.query(
      `select public.save_award_group_configuration($1,$2,$3,$4,$5,$6::jsonb)`,
      [2026, '100/2026', '2026-08-01', 'Ψ-TEST', 30000, groupPayload]
    );
    assert.equal(await scalar(db,`select public.app_award_group_configuration_is_canonical(2026)`),true);
    assert.deepEqual(
      (await db.query(`select group_no, array_agg(municipal_unit_id order by municipal_unit_id) as members from public.app_rhodes_award_group_template() group by group_no order by group_no`)).rows,
      [
        {group_no:1,members:[1]},
        {group_no:2,members:[2,3,4]},
        {group_no:3,members:[5,6,7]},
        {group_no:4,members:[8,9,10]}
      ]
    );

    const materialIds = (await db.query(`select id,code from public.materials order by id`)).rows;
    const m1 = String(materialIds.find(x => x.code === 'M1').id);
    const m2 = String(materialIds.find(x => x.code === 'M2').id);
    const m3 = String(materialIds.find(x => x.code === 'M3').id);

    const group2Committed = JSON.stringify([{ material_id: m2, quantity: 200, unit_price: 100, comments: null }]);
    const group2Study = (await db.query(
      `select public.lock_study_atomic(null,3,10,2026,null,null,null,$1::jsonb) as result`,
      [group2Committed]
    )).rows[0].result.study_id;
    const group2Overflow = JSON.stringify([{ material_id: m2, quantity: 101, unit_price: 100, comments: null }]);
    await assert.rejects(
      db.query(`select public.lock_study_atomic(null,4,10,2026,null,null,null,$1::jsonb)`, [group2Overflow]),
      /υπερβαίνει το όριο/i,
      'οι 20.000 € της Καλλιθέας και οι 10.100 € της Αφάντου ελέγχονται στο κοινό όριο της ομάδας 2'
    );
    await db.query(`select public.cancel_locked_study_atomic($1,'Ολοκλήρωση δοκιμής κοινού ορίου')`, [group2Study]);

    const issuedTicket=(await db.query(
      `select public.issue_excel_export_token(1,10,2028,3) as result`
    )).rows[0].result;
    const excelToken=issuedTicket.token;
    assert.match(excelToken,/^[0-9a-f-]{36}$/i);
    await db.exec(`select set_config('request.jwt.claim.sub','${OTHER_ADMIN_ID}',false);`);
    await assert.rejects(
      db.query(
        `select public.secure_import_catalog_request_atomic($1,null,1,10,2028,'Ξένο δελτίο','[]'::jsonb,'[]'::jsonb,'[]'::jsonb)`,
        [excelToken]
      ),
      /διαφορετικό χρήστη/i
    );
    await db.exec(`select set_config('request.jwt.claim.sub','${ADMIN_ID}',false);`);
    assert.equal(await scalar(db,`select used_at is null from public.app_excel_import_tokens where token=$1`,[excelToken]),true,
      'το δελτίο δεν καταναλώνεται από διαφορετικό διαχειριστή');
    await assert.rejects(
      db.query(
        `select public.secure_import_catalog_request_atomic($1,null,1,10,2028,'Excel 2028',$2::jsonb,'[]'::jsonb,'[]'::jsonb)`,
        [excelToken,JSON.stringify([{id:m1,patch:{name:'Χ'.repeat(501)}}])]
      ),
      /υπερβολικά μεγάλο κείμενο/i
    );
    assert.equal(await scalar(db,`select used_at is null from public.app_excel_import_tokens where token=$1`,[excelToken]),true,
      'αποτυχημένη εισαγωγή δεν καταναλώνει το δελτίο προέλευσης');
    const secureExcelLines=JSON.stringify([{material_id:m3,quantity:0.4,unit_price:10,comments:null}]);
    const secureImport=(await db.query(
      `select public.secure_import_catalog_request_atomic($1,null,1,10,2028,'Excel 2028','[]'::jsonb,'[]'::jsonb,$2::jsonb) as result`,
      [excelToken,secureExcelLines]
    )).rows[0].result;
    assert.equal(secureImport.secure_import,true);
    assert.equal(Number(await scalar(db,`select quantity from public.request_lines where request_id=$1`,[secureImport.request_id])),0.4);
    assert.equal(await scalar(db,`select used_at is not null from public.app_excel_import_tokens where token=$1`,[excelToken]),true);
    await assert.rejects(
      db.query(
        `select public.secure_import_catalog_request_atomic($1,null,1,10,2028,'Excel 2028','[]'::jsonb,'[]'::jsonb,$2::jsonb)`,
        [excelToken,secureExcelLines]
      ),
      /ήδη χρησιμοποιηθεί/i
    );
    assert.equal(await scalar(db,`
      select has_function_privilege('authenticated',
        'public.import_catalog_request_atomic(text,bigint,bigint,integer,text,jsonb,jsonb,jsonb)','EXECUTE')
    `),false,'το παλιό RPC εισαγωγής δεν είναι προσβάσιμο από browser');
    assert.equal(await scalar(db,`select has_table_privilege('authenticated','public.app_excel_import_tokens','SELECT')`),false);

    const decimalLine = JSON.stringify([{ material_id: m3, quantity: 0.4, unit_price: 10, comments: null }]);
    const decimalSave = await db.query(
      `select public.save_unit_request_atomic(null,1,10,2027,'Δεκαδικές ποσότητες','save',$1::jsonb) as result`,
      [decimalLine]
    );
    const decimalRequest = decimalSave.rows[0].result.request_id;
    assert.equal(Number(await scalar(db, `select quantity from public.request_lines where request_id=$1`, [decimalRequest])), 0.4,
      'η ποσότητα 0,4 m διατηρείται χωρίς στρογγυλοποίηση');
    await assert.rejects(
      db.query(
        `select public.save_unit_request_atomic($1,1,10,2027,'Δεκαδικές ποσότητες','save',$2::jsonb)`,
        [decimalRequest, JSON.stringify([{ material_id: m1, quantity: 1.5, unit_price: 100, comments: null }])]
      ),
      /μόνο ακέραιες ποσότητες/i
    );
    assert.equal(Number(await scalar(db, `select quantity from public.request_lines where request_id=$1`, [decimalRequest])), 0.4,
      'η αποτυχημένη ακέραιη ποσότητα δεν αλλοιώνει την αποθηκευμένη δεκαδική γραμμή');
    const oneLine = JSON.stringify([{ material_id: m1, quantity: 1, unit_price: 100, comments: null }]);

    const save1 = await db.query(
      `select public.save_unit_request_atomic(null,1,10,2026,'Δελτίο 2026','save',$1::jsonb) as result`,
      [oneLine]
    );
    const request1 = save1.rows[0].result.request_id;
    assert.equal(Number(await scalar(db, `select quantity from public.request_lines where request_id=$1`, [request1])), 1);

    await assert.rejects(
      db.query(
        `select public.save_unit_request_atomic($1,1,10,2026,'Δελτίο 2026','save',$2::jsonb)`,
        [request1, JSON.stringify([{ material_id: '999999', quantity: 5, unit_price: 100, comments: null }])]
      ),
      /άγνωστο|ξένο/i
    );
    assert.equal(Number(await scalar(db, `select quantity from public.request_lines where request_id=$1`, [request1])), 1,
      'αποτυχημένη αποθήκευση δεν αλλάζει τις προηγούμενες γραμμές');

    const locked1 = await db.query(
      `select public.lock_study_atomic($1,1,10,2026,null,null,null,$2::jsonb) as result`,
      [request1, oneLine]
    );
    const study1 = locked1.rows[0].result.study_id;
    await db.query(`select public.cancel_locked_study_atomic($1,'Ακύρωση δοκιμής')`, [study1]);
    assert.equal(await scalar(db, `select record_status from public.locked_studies where id=$1`, [study1]), 'cancelled');
    assert.equal(Number(await scalar(db, `select count(*) from public.locked_studies where id=$1`, [study1])), 1,
      'η ακύρωση δεν διαγράφει το ιστορικό');
    await assert.rejects(db.query(`delete from public.locked_studies where id=$1`, [study1]), /δεν διαγράφεται/i);

    const studyLines = JSON.stringify([
      { material_id: m1, quantity: 1, unit_price: 100, comments: null },
      { material_id: m2, quantity: 9, unit_price: 100, comments: null },
      { material_id: m3, quantity: 0.4, unit_price: 10, comments: null }
    ]);
    const save2 = await db.query(
      `select public.save_unit_request_atomic(null,1,10,2026,'Δελτίο 2026','save',$1::jsonb) as result`,
      [studyLines]
    );
    const locked2 = await db.query(
      `select public.lock_study_atomic($1,1,10,2026,null,null,null,$2::jsonb) as result`,
      [save2.rows[0].result.request_id, studyLines]
    );
    const study2 = locked2.rows[0].result.study_id;

    const tooLarge = JSON.stringify([{ material_id: m2, quantity: 291, unit_price: 100, comments: null }]);
    await assert.rejects(
      db.query(`select public.lock_study_atomic(null,1,10,2026,null,null,null,$1::jsonb)`, [tooLarge]),
      /υπερβαίνει το όριο/i
    );
    assert.equal(Number(await scalar(db, `select count(*) from public.locked_studies where record_status='active'`)), 1,
      'αποτυχημένο κλείδωμα δεν δημιουργεί μερική μελέτη');

    const supplier = await scalar(db, `insert into public.mo_suppliers(name,email) values ('Προμηθευτής','p@example.test') returning id`);
    const contractResult = await db.query(
      `select public.save_contract_atomic(null,$1,$2,'Σύμβαση δοκιμής','26SYMVTEST','1/2026','2026-08-01','2026-12-31',24) as result`,
      [study2, String(supplier)]
    );
    const contractId = contractResult.rows[0].result.contract_id;
    assert.equal(Number(await scalar(db, `select count(*) from public.mo_contract_items where contract_id=$1`, [contractId])), 3);
    const citem1 = String(await scalar(db, `select id from public.mo_contract_items where contract_id=$1 and code='M1'`, [contractId]));
    const citem3 = String(await scalar(db, `select id from public.mo_contract_items where contract_id=$1 and code='M3'`, [contractId]));

    const invalidOrder = JSON.stringify([{
      contract_item_id: citem1, is_custom: false, description: 'Υλικό 1', unit: 'τεμ.',
      quantity: 2, unit_price: 100, mapping: null
    }]);
    await assert.rejects(
      db.query(
        `select public.save_order_atomic(null,$1,'2026-08-05',null,'Δοκιμή','',24,$2::jsonb,true)`,
        [study2, invalidOrder]
      ),
      /Υπέρβαση συμβατικής ποσότητας/i
    );
    assert.equal(Number(await scalar(db, `select count(*) from public.mo_orders`)), 1,
      'αποτυχημένη έκδοση δεν αφήνει κεφαλίδα ή γραμμές δελτίου');

    const validOrder = JSON.stringify([
      {
        contract_item_id: citem1, is_custom: false, description: 'Υλικό 1', unit: 'τεμ.',
        quantity: 1, unit_price: 100, mapping: null
      },
      {
        contract_item_id: citem3, is_custom: false, description: 'Καλώδιο σε μέτρα', unit: 'm',
        quantity: 0.15, unit_price: 10, mapping: null
      }
    ]);
    const issued = await db.query(
      `select public.save_order_atomic(null,$1,'2026-08-05',null,'Δοκιμή','',24,$2::jsonb,true) as result`,
      [study2, validOrder]
    );
    const orderId = issued.rows[0].result.order_id;
    assert.equal(issued.rows[0].result.status, 'issued');
    assert.equal(issued.rows[0].result.order_no, 'ΔΥ-2026-01-008');

    let balance = (await db.query(
      `select public.get_contract_balance_atomic($1) as result`, [contractId]
    )).rows[0].result;
    const balanceM3 = balance.items.find(x => x.contract_item_id === citem3);
    assert.equal(Number(balanceM3.committed_qty), 0.15);
    assert.equal(Number(balanceM3.remaining_qty), 0.25);
    assert.equal(Number(balance.open_net), 101.5);

    await db.query(`select public.transition_order_status_atomic($1,'sent',null)`, [orderId]);
    await db.query(`select public.transition_order_status_atomic($1,'received',null)`, [orderId]);
    balance = (await db.query(`select public.get_contract_balance_atomic($1) as result`, [contractId])).rows[0].result;
    assert.equal(Number(balance.open_net), 0);
    assert.equal(Number(balance.received_net), 101.5);
    await db.query(`select public.transition_order_status_atomic($1,'cancelled','Διοικητική ακύρωση δοκιμής')`, [orderId]);
    assert.equal(await scalar(db, `select status from public.mo_orders where id=$1`, [orderId]), 'cancelled');
    balance = (await db.query(`select public.get_contract_balance_atomic($1) as result`, [contractId])).rows[0].result;
    assert.equal(Number(balance.committed_net), 0, 'η ακύρωση αποδεσμεύει την οικονομική αξία');
    assert.equal(Number(balance.items.find(x => x.contract_item_id === citem3).remaining_qty), 0.4,
      'η ακύρωση αποδεσμεύει τη συμβατική ποσότητα');

    const fractionalPiece = JSON.stringify([{
      contract_item_id: citem1, is_custom: false, description: 'Υλικό 1', unit: 'τεμ.',
      quantity: 0.5, unit_price: 100, mapping: null
    }]);
    await assert.rejects(
      db.query(
        `select public.save_order_atomic(null,$1,'2026-08-06',null,'Δοκιμή ακέραιας μονάδας','',24,$2::jsonb,true)`,
        [study2, fractionalPiece]
      ),
      /Μη έγκυρη ποσότητα|ακέραι/i
    );
    await assert.rejects(db.query(`update public.mo_orders set usage_location='Αλλοίωση' where id=$1`, [orderId]), /αμετάβλητο/i);
    await assert.rejects(db.query(`delete from public.mo_orders where id=$1`, [orderId]), /δεν διαγράφεται/i);

    assert.ok(Number(await scalar(db, `select count(*) from public.app_audit_log`)) >= 8);
    await assert.rejects(db.exec(`delete from public.app_audit_log`), /αμετάβλητο ιστορικό/i);
    await assert.rejects(db.exec(`delete from public.saved_versions`), /αμετάβλητο ιστορικό/i);

    const policyCount = Number(await scalar(db, `
      select count(*) from pg_policies
      where schemaname='public' and tablename in (
        'profiles','materials','unit_requests','request_lines','saved_versions','locked_studies',
        'award_group_configurations','award_groups','award_group_memberships','user_app_permissions',
        'app_audit_log','mo_suppliers','mo_receivers','mo_contracts','mo_contract_items','mo_orders','mo_order_items'
      )
    `));
    assert.ok(policyCount >= 17, 'έχουν δημιουργηθεί πολιτικές RLS για όλα τα λειτουργικά δεδομένα');
    assert.equal(await scalar(db,`select relrowsecurity from pg_class where oid='public.app_excel_import_tokens'::regclass`),true);
    assert.equal(await scalar(db, `select has_table_privilege('authenticated','public.unit_requests','INSERT')`), false);
    assert.equal(await scalar(db, `select has_table_privilege('authenticated','public.mo_orders','UPDATE')`), false);

    await db.exec(`
      insert into auth.users(id,email) values ('${UNIT2_ID}','unit2@example.test');
      insert into public.profiles(id,role,municipal_unit_id,full_name,email)
        values ('${UNIT2_ID}','unit_user',2,'Χρήστης Ιαλυσού','unit2@example.test');
      set role authenticated;
      select set_config('request.jwt.claim.sub','${UNIT2_ID}',false);
    `);
    assert.equal(Number(await scalar(db, `select count(*) from public.locked_studies`)), 0,
      'το RLS δεν αποκαλύπτει σε χρήστη άλλης Δ.Ε. τις κλειδωμένες μελέτες της Ρόδου');
    await assert.rejects(
      db.query(
        `select public.save_unit_request_atomic(null,1,10,2026,'Ξένο αίτημα','save',$1::jsonb)`,
        [oneLine]
      ),
      /δικαίωμα εγγραφής/i
    );
    await assert.rejects(
      db.exec(`insert into public.unit_requests(municipal_unit_id,group_id,request_year) values (2,10,2027)`),
      /permission denied/i
    );
    await db.exec(`reset role; select set_config('request.jwt.claim.sub','${ADMIN_ID}',false);`);
  } finally {
    await db.close();
  }
});
