begin;

-- v36.1 — Άρθρο 636 Κώδικα Τοπικής Αυτοδιοίκησης.
-- Η κατανομή αποθηκεύεται ανά οικονομικό έτος και προέρχεται αποκλειστικά
-- από ενεργή απόφαση Δημοτικού Συμβουλίου. Η εγγραφή με id = 11 αποτελεί
-- τη συγκεντρωτική, εικονική μονάδα «Δήμος Ρόδου» της υφιστάμενης εφαρμογής.

create table if not exists public.award_group_configurations (
  id bigint generated by default as identity primary key,
  budget_year integer not null unique check (budget_year between 2023 and 2100),
  decision_number text not null check (length(btrim(decision_number)) > 0),
  decision_date date not null,
  decision_ada text not null check (length(btrim(decision_ada)) > 0),
  direct_award_cap numeric(14,2) not null default 30000.00 check (direct_award_cap > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null references auth.users(id),
  updated_by uuid null references auth.users(id)
);

create table if not exists public.award_groups (
  id bigint generated by default as identity primary key,
  configuration_id bigint not null references public.award_group_configurations(id) on delete cascade,
  group_no smallint not null check (group_no between 1 and 4),
  name text not null check (length(btrim(name)) > 0),
  unique (configuration_id, group_no),
  unique (id, configuration_id)
);

create table if not exists public.award_group_memberships (
  configuration_id bigint not null references public.award_group_configurations(id) on delete cascade,
  award_group_id bigint not null,
  municipal_unit_id bigint not null references public.municipal_units(id),
  primary key (configuration_id, municipal_unit_id),
  unique (award_group_id, municipal_unit_id),
  foreign key (award_group_id, configuration_id)
    references public.award_groups(id, configuration_id) on delete cascade
);

alter table public.locked_studies
  add column if not exists award_group_id bigint null references public.award_groups(id) on delete restrict;

create index if not exists idx_award_groups_configuration
  on public.award_groups(configuration_id, group_no);
create index if not exists idx_award_memberships_group
  on public.award_group_memberships(award_group_id, municipal_unit_id);
create index if not exists idx_locked_studies_award_cap
  on public.locked_studies(award_group_id, group_id, request_year);

alter table public.award_group_configurations enable row level security;
alter table public.award_groups enable row level security;
alter table public.award_group_memberships enable row level security;

drop policy if exists award_group_configurations_read_authenticated on public.award_group_configurations;
create policy award_group_configurations_read_authenticated
  on public.award_group_configurations for select to authenticated using (true);

drop policy if exists award_groups_read_authenticated on public.award_groups;
create policy award_groups_read_authenticated
  on public.award_groups for select to authenticated using (true);

drop policy if exists award_group_memberships_read_authenticated on public.award_group_memberships;
create policy award_group_memberships_read_authenticated
  on public.award_group_memberships for select to authenticated using (true);

revoke all on public.award_group_configurations from anon, authenticated;
revoke all on public.award_groups from anon, authenticated;
revoke all on public.award_group_memberships from anon, authenticated;
grant select on public.award_group_configurations to authenticated;
grant select on public.award_groups to authenticated;
grant select on public.award_group_memberships to authenticated;

create or replace function public.save_award_group_configuration(
  p_budget_year integer,
  p_decision_number text,
  p_decision_date date,
  p_decision_ada text,
  p_direct_award_cap numeric,
  p_groups jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_configuration_id bigint;
  v_group jsonb;
  v_group_id bigint;
  v_group_no integer;
  v_group_name text;
  v_member_text text;
  v_member_id bigint;
  v_group_numbers integer[] := array[]::integer[];
  v_member_ids bigint[] := array[]::bigint[];
  v_has_locked_studies boolean := false;
begin
  if auth.uid() is null or not exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and lower(p.role::text) = 'admin'
  ) then
    raise exception using errcode = '42501', message = 'Μόνο διαχειριστής μπορεί να ορίσει τις ομάδες Δημοτικών Ενοτήτων.';
  end if;

  if p_budget_year < 2023 or p_budget_year > 2100 then
    raise exception 'Μη έγκυρο οικονομικό έτος.';
  end if;
  if nullif(btrim(p_decision_number), '') is null
     or p_decision_date is null
     or nullif(btrim(p_decision_ada), '') is null then
    raise exception 'Απαιτούνται αριθμός απόφασης, ημερομηνία και ΑΔΑ.';
  end if;
  if p_direct_award_cap is null or p_direct_award_cap <= 0 then
    raise exception 'Το καθαρό όριο πρέπει να είναι θετικό.';
  end if;
  if p_groups is null or jsonb_typeof(p_groups) <> 'array'
     or jsonb_array_length(p_groups) < 1
     or jsonb_array_length(p_groups) > 4 then
    raise exception 'Η κατανομή πρέπει να περιλαμβάνει από μία έως τέσσερις ομάδες.';
  end if;

  -- Πλήρης επικύρωση πριν από οποιαδήποτε μεταβολή.
  for v_group in select value from jsonb_array_elements(p_groups)
  loop
    v_group_no := nullif(v_group ->> 'group_no', '')::integer;
    v_group_name := btrim(coalesce(v_group ->> 'name', ''));
    if v_group_no is null or v_group_no < 1 or v_group_no > 4 then
      raise exception 'Κάθε αριθμός ομάδας πρέπει να είναι από 1 έως 4.';
    end if;
    if v_group_no = any(v_group_numbers) then
      raise exception 'Ο αριθμός ομάδας % εμφανίζεται περισσότερες από μία φορές.', v_group_no;
    end if;
    if v_group_name = '' then
      raise exception 'Κάθε χρησιμοποιούμενη ομάδα πρέπει να έχει ονομασία.';
    end if;
    if jsonb_typeof(v_group -> 'municipal_unit_ids') <> 'array'
       or jsonb_array_length(v_group -> 'municipal_unit_ids') < 1 then
      raise exception 'Κάθε ομάδα πρέπει να περιλαμβάνει τουλάχιστον μία Δημοτική Ενότητα.';
    end if;
    v_group_numbers := array_append(v_group_numbers, v_group_no);
    for v_member_text in select value from jsonb_array_elements_text(v_group -> 'municipal_unit_ids')
    loop
      v_member_id := v_member_text::bigint;
      if v_member_id = any(v_member_ids) then
        raise exception 'Η Δημοτική Ενότητα % έχει αντιστοιχιστεί περισσότερες από μία φορές.', v_member_id;
      end if;
      v_member_ids := array_append(v_member_ids, v_member_id);
    end loop;
  end loop;

  if exists (
    select 1 from public.municipal_units mu
    where mu.id <> 11 and not (mu.id::bigint = any(v_member_ids))
  ) then
    raise exception 'Κάθε Δημοτική Ενότητα πρέπει να αντιστοιχιστεί ακριβώς σε μία ομάδα.';
  end if;
  if exists (
    select 1 from unnest(v_member_ids) x(unit_id)
    where not exists (
      select 1 from public.municipal_units mu where mu.id::bigint = x.unit_id and mu.id <> 11
    )
  ) then
    raise exception 'Η κατανομή περιέχει άγνωστη ή μη επιτρεπτή Δημοτική Ενότητα.';
  end if;

  select c.id into v_configuration_id
  from public.award_group_configurations c
  where c.budget_year = p_budget_year
  for update;

  if v_configuration_id is not null then
    select exists (
      select 1 from public.locked_studies ls
      where ls.request_year = p_budget_year and ls.municipal_unit_id <> 11
    ) into v_has_locked_studies;
    if v_has_locked_studies then
      raise exception 'Η κατανομή του % δεν αλλάζει επειδή υπάρχουν ήδη κλειδωμένες μελέτες. Απαιτείται ελεγχόμενη διοικητική διαδικασία μεταβολής.', p_budget_year;
    end if;
    update public.award_group_configurations
      set decision_number = btrim(p_decision_number),
          decision_date = p_decision_date,
          decision_ada = upper(btrim(p_decision_ada)),
          direct_award_cap = round(p_direct_award_cap, 2),
          is_active = true,
          updated_at = now(),
          updated_by = auth.uid()
      where id = v_configuration_id;
    delete from public.award_groups where configuration_id = v_configuration_id;
  else
    insert into public.award_group_configurations (
      budget_year, decision_number, decision_date, decision_ada, direct_award_cap,
      is_active, created_by, updated_by
    ) values (
      p_budget_year, btrim(p_decision_number), p_decision_date, upper(btrim(p_decision_ada)),
      round(p_direct_award_cap, 2), true, auth.uid(), auth.uid()
    ) returning id into v_configuration_id;
  end if;

  for v_group in select value from jsonb_array_elements(p_groups)
  loop
    v_group_no := (v_group ->> 'group_no')::integer;
    v_group_name := btrim(v_group ->> 'name');
    insert into public.award_groups (configuration_id, group_no, name)
      values (v_configuration_id, v_group_no, v_group_name)
      returning id into v_group_id;

    for v_member_text in select value from jsonb_array_elements_text(v_group -> 'municipal_unit_ids')
    loop
      insert into public.award_group_memberships (configuration_id, award_group_id, municipal_unit_id)
        values (v_configuration_id, v_group_id, v_member_text::bigint);
    end loop;
  end loop;

  -- Πρώτη εγκατάσταση πάνω σε υπάρχον ιστορικό v36: οι παλιές μελέτες
  -- λαμβάνουν την ομάδα που ορίζει η απόφαση για το ίδιο οικονομικό έτος.
  update public.locked_studies ls
    set award_group_id = m.award_group_id
    from public.award_group_memberships m
    where m.configuration_id = v_configuration_id
      and ls.request_year = p_budget_year
      and ls.municipal_unit_id = m.municipal_unit_id
      and ls.award_group_id is null;

  return v_configuration_id;
end;
$$;

revoke all on function public.save_award_group_configuration(integer,text,date,text,numeric,jsonb) from public, anon;
grant execute on function public.save_award_group_configuration(integer,text,date,text,numeric,jsonb) to authenticated;

comment on table public.award_group_configurations is
  'Ετήσια απόφαση Δημοτικού Συμβουλίου για τις ομάδες Δημοτικών Ενοτήτων του άρθρου 636.';
comment on column public.locked_studies.award_group_id is
  'Αμετάβλητη ομάδα Δημοτικών Ενοτήτων στην οποία προσμετρήθηκε η κλειδωμένη μελέτη.';

commit;
