begin;

-- v36.2 / Βήμα 2A
-- Κεντρικά δικαιώματα, πλήρες RLS και αμετάβλητο ιστορικό.
-- Η migration εφαρμόζεται μετά την 202608040001_award_groups.sql.

create table if not exists public.user_app_permissions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  can_supervise boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id)
);

alter table public.locked_studies
  add column if not exists record_status text not null default 'active',
  add column if not exists cancelled_at timestamptz null,
  add column if not exists cancelled_by uuid null references auth.users(id),
  add column if not exists cancellation_reason text null;

alter table public.mo_orders
  add column if not exists cancelled_at timestamptz null,
  add column if not exists cancelled_by uuid null references auth.users(id),
  add column if not exists cancellation_reason text null;

alter table public.mo_suppliers
  add column if not exists created_by uuid null references auth.users(id),
  add column if not exists updated_by uuid null references auth.users(id),
  add column if not exists updated_at timestamptz not null default now();

alter table public.mo_receivers
  add column if not exists created_by uuid null references auth.users(id),
  add column if not exists updated_by uuid null references auth.users(id),
  add column if not exists updated_at timestamptz not null default now();

alter table public.mo_contracts
  add column if not exists updated_by uuid null references auth.users(id),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.locked_studies'::regclass
      and conname = 'locked_studies_record_status_check'
  ) then
    alter table public.locked_studies
      add constraint locked_studies_record_status_check
      check (record_status in ('active', 'cancelled')) not valid;
    alter table public.locked_studies validate constraint locked_studies_record_status_check;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.mo_orders'::regclass
      and conname = 'mo_orders_cancellation_reason_check'
  ) then
    alter table public.mo_orders
      add constraint mo_orders_cancellation_reason_check
      check (
        status <> 'cancelled'
        or (
          cancelled_at is not null
          and cancelled_by is not null
          and nullif(btrim(cancellation_reason), '') is not null
        )
      ) not valid;
  end if;
end;
$$;

create index if not exists idx_locked_studies_active_cap
  on public.locked_studies (award_group_id, group_id, request_year, record_status);
create index if not exists idx_user_app_permissions_supervise
  on public.user_app_permissions (user_id, can_supervise);

create table if not exists public.app_audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid null references auth.users(id),
  actor_role text null,
  event_type text not null check (length(btrim(event_type)) > 0),
  entity_type text not null check (length(btrim(entity_type)) > 0),
  entity_id text null,
  municipal_unit_id bigint null references public.municipal_units(id),
  reason text null,
  before_data jsonb null,
  after_data jsonb null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_app_audit_entity
  on public.app_audit_log (entity_type, entity_id, occurred_at desc);
create index if not exists idx_app_audit_unit
  on public.app_audit_log (municipal_unit_id, occurred_at desc);
create index if not exists idx_app_audit_actor
  on public.app_audit_log (actor_user_id, occurred_at desc);

create or replace function public.app_current_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select lower(coalesce(p.role::text, ''))
  from public.profiles p
  where p.id = auth.uid()
  limit 1
$$;

create or replace function public.app_current_unit_id()
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select p.municipal_unit_id::bigint
  from public.profiles p
  where p.id = auth.uid()
  limit 1
$$;

create or replace function public.app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select auth.uid() is not null and public.app_current_role() = 'admin'
$$;

create or replace function public.app_can_supervise()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select auth.uid() is not null and (
    public.app_is_admin()
    or exists (
      select 1
      from public.user_app_permissions p
      where p.user_id = auth.uid() and p.can_supervise
    )
  )
$$;

create or replace function public.app_can_read_unit(p_municipal_unit_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select auth.uid() is not null and (
    public.app_can_supervise()
    or public.app_current_role() in ('admin', 'central', 'viewer')
    or (
      public.app_current_role() = 'unit_user'
      and public.app_current_unit_id() = p_municipal_unit_id
    )
  )
$$;

create or replace function public.app_can_write_unit(p_municipal_unit_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
set row_security = off
as $$
  select auth.uid() is not null and (
    public.app_is_admin()
    or (
      public.app_current_role() = 'unit_user'
      and public.app_current_unit_id() = p_municipal_unit_id
    )
  )
$$;

create or replace function public.app_write_audit(
  p_event_type text,
  p_entity_type text,
  p_entity_id text,
  p_municipal_unit_id bigint,
  p_reason text,
  p_before_data jsonb,
  p_after_data jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_id bigint;
begin
  insert into public.app_audit_log (
    actor_user_id, actor_role, event_type, entity_type, entity_id,
    municipal_unit_id, reason, before_data, after_data, metadata
  ) values (
    auth.uid(), public.app_current_role(), btrim(p_event_type), btrim(p_entity_type),
    p_entity_id, p_municipal_unit_id, nullif(btrim(coalesce(p_reason, '')), ''),
    p_before_data, p_after_data, coalesce(p_metadata, '{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.app_write_audit(text,text,text,bigint,text,jsonb,jsonb,jsonb)
  from public, anon, authenticated;

create or replace function public.app_immutable_history_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception using
    errcode = '55000',
    message = 'Η εγγραφή αποτελεί αμετάβλητο ιστορικό και δεν επιτρέπεται να τροποποιηθεί ή να διαγραφεί.';
end;
$$;

drop trigger if exists trg_app_audit_log_immutable on public.app_audit_log;
create trigger trg_app_audit_log_immutable
  before update or delete on public.app_audit_log
  for each row execute function public.app_immutable_history_guard();

drop trigger if exists trg_saved_versions_immutable on public.saved_versions;
create trigger trg_saved_versions_immutable
  before update or delete on public.saved_versions
  for each row execute function public.app_immutable_history_guard();

create or replace function public.app_locked_study_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    raise exception using
      errcode = '55000',
      message = 'Η κλειδωμένη μελέτη δεν διαγράφεται. Χρησιμοποιήστε ελεγχόμενη ακύρωση με αιτιολογία.';
  end if;

  if (
    to_jsonb(new) - array[
      'supplier_name', 'kimdis_url', 'record_status', 'award_group_id',
      'cancelled_at', 'cancelled_by', 'cancellation_reason'
    ]::text[]
  ) is distinct from (
    to_jsonb(old) - array[
      'supplier_name', 'kimdis_url', 'record_status', 'award_group_id',
      'cancelled_at', 'cancelled_by', 'cancellation_reason'
    ]::text[]
  ) then
    raise exception using
      errcode = '55000',
      message = 'Τα οικονομικά στοιχεία και το στιγμιότυπο κλειδωμένης μελέτης είναι αμετάβλητα.';
  end if;

  -- Ελεγχόμενη, εφάπαξ αντιστοίχιση παλαιών εγγραφών από τη migration v36.1.
  -- Μετά τη συμπλήρωση, η ομάδα δεν μπορεί να αλλάξει.
  if new.award_group_id is distinct from old.award_group_id and not (
    old.award_group_id is null
    and new.award_group_id is not null
    and public.app_is_admin()
    and exists (
      select 1
      from public.award_group_configurations c
      join public.award_group_memberships m on m.configuration_id = c.id
      where c.budget_year = old.request_year
        and c.is_active
        and m.municipal_unit_id = old.municipal_unit_id
        and m.award_group_id = new.award_group_id
    )
  ) then
    raise exception using
      errcode = '55000',
      message = 'Η ομάδα Δημοτικών Ενοτήτων κλειδωμένης μελέτης δεν αλλάζει.';
  end if;

  if old.record_status = 'cancelled' then
    raise exception using
      errcode = '55000',
      message = 'Ακυρωμένη κλειδωμένη μελέτη δεν μεταβάλλεται.';
  end if;

  if new.record_status not in ('active', 'cancelled') then
    raise exception 'Μη επιτρεπτή κατάσταση κλειδωμένης μελέτης.';
  end if;

  if new.record_status = 'cancelled' and (
    new.cancelled_at is null
    or new.cancelled_by is null
    or nullif(btrim(coalesce(new.cancellation_reason, '')), '') is null
  ) then
    raise exception 'Η ακύρωση απαιτεί χρόνο, χρήστη και αιτιολογία.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_locked_studies_immutable on public.locked_studies;
create trigger trg_locked_studies_immutable
  before update or delete on public.locked_studies
  for each row execute function public.app_locked_study_guard();

create or replace function public.app_order_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'draft' then
      raise exception using
        errcode = '55000',
        message = 'Εκδοθέν δελτίο δεν διαγράφεται. Επιτρέπεται μόνο ακύρωση με αιτιολογία.';
    end if;
    return old;
  end if;

  if old.status <> 'draft' and (
    to_jsonb(new) - array[
      'status', 'sent_at', 'received_at',
      'cancelled_at', 'cancelled_by', 'cancellation_reason'
    ]::text[]
  ) is distinct from (
    to_jsonb(old) - array[
      'status', 'sent_at', 'received_at',
      'cancelled_at', 'cancelled_by', 'cancellation_reason'
    ]::text[]
  ) then
    raise exception using
      errcode = '55000',
      message = 'Το περιεχόμενο εκδοθέντος δελτίου είναι αμετάβλητο.';
  end if;

  if new.status is distinct from old.status and not (
    (old.status = 'draft' and new.status = 'issued')
    or (old.status = 'issued' and new.status in ('sent', 'cancelled'))
    or (old.status = 'sent' and new.status in ('received', 'cancelled'))
    or (old.status = 'received' and new.status = 'cancelled')
  ) then
    raise exception 'Μη επιτρεπτή μετάβαση δελτίου από % σε %.', old.status, new.status;
  end if;

  if new.status = 'cancelled' and (
    new.cancelled_at is null
    or new.cancelled_by is null
    or nullif(btrim(coalesce(new.cancellation_reason, '')), '') is null
  ) then
    raise exception 'Η ακύρωση δελτίου απαιτεί χρόνο, χρήστη και αιτιολογία.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_mo_orders_immutable on public.mo_orders;
create trigger trg_mo_orders_immutable
  before update or delete on public.mo_orders
  for each row execute function public.app_order_guard();

create or replace function public.app_order_item_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_order_id text;
  v_status text;
begin
  v_order_id := case when tg_op = 'DELETE' then old.order_id::text else new.order_id::text end;
  select o.status into v_status
  from public.mo_orders o
  where o.id::text = v_order_id;

  if v_status is distinct from 'draft' then
    raise exception using
      errcode = '55000',
      message = 'Οι γραμμές εκδοθέντος δελτίου είναι αμετάβλητες.';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists trg_mo_order_items_immutable on public.mo_order_items;
create trigger trg_mo_order_items_immutable
  before update or delete on public.mo_order_items
  for each row execute function public.app_order_item_guard();

create or replace function public.app_contract_item_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception using
    errcode = '55000',
    message = 'Το αρχικό τιμολόγιο της ανάθεσης αποτελεί αμετάβλητο στιγμιότυπο της κλειδωμένης μελέτης.';
end;
$$;

drop trigger if exists trg_mo_contract_items_immutable on public.mo_contract_items;
create trigger trg_mo_contract_items_immutable
  before update or delete on public.mo_contract_items
  for each row execute function public.app_contract_item_guard();

create or replace function public.app_contract_guard()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    raise exception using
      errcode = '55000',
      message = 'Η ανάθεση δεν διαγράφεται. Απαιτείται ελεγχόμενη διοικητική μεταβολή.';
  end if;

  if (
    to_jsonb(new) - array[
      'supplier_id', 'adam', 'protocol_no', 'start_date', 'end_date',
      'active', 'updated_at', 'updated_by'
    ]::text[]
  ) is distinct from (
    to_jsonb(old) - array[
      'supplier_id', 'adam', 'protocol_no', 'start_date', 'end_date',
      'active', 'updated_at', 'updated_by'
    ]::text[]
  ) then
    raise exception using
      errcode = '55000',
      message = 'Η πηγή, η Δημοτική Ενότητα και το οικονομικό αντικείμενο της ανάθεσης είναι αμετάβλητα.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_mo_contracts_immutable on public.mo_contracts;
create trigger trg_mo_contracts_immutable
  before update or delete on public.mo_contracts
  for each row execute function public.app_contract_guard();

create or replace function public.app_generic_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_before jsonb;
  v_after jsonb;
  v_row jsonb;
  v_id text;
  v_unit bigint;
begin
  v_before := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  v_after := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  v_row := coalesce(v_after, v_before, '{}'::jsonb);
  v_id := coalesce(v_row ->> 'id', v_row ->> 'user_id');
  if coalesce(v_row ->> 'municipal_unit_id', '') ~ '^[0-9]+$' then
    v_unit := (v_row ->> 'municipal_unit_id')::bigint;
  end if;

  perform public.app_write_audit(
    lower(tg_op), tg_table_name, v_id, v_unit, null,
    v_before, v_after, jsonb_build_object('source', 'row_trigger')
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'materials', 'tender_overrides', 'mo_suppliers', 'mo_receivers',
    'award_group_configurations', 'award_groups', 'award_group_memberships'
  ]
  loop
    execute format('drop trigger if exists %I on public.%I', 'trg_' || v_table || '_audit', v_table);
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.app_generic_audit_trigger()',
      'trg_' || v_table || '_audit', v_table
    );
  end loop;
end;
$$;

-- Καθαρισμός κάθε παλαιάς πολιτικής: οι PostgreSQL permissive policies
-- συνδυάζονται με OR, άρα μια ξεχασμένη παλιά πολιτική θα ακύρωνε το νέο RLS.
do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(array[
        'profiles', 'municipal_units', 'procurement_groups', 'materials',
        'unit_requests', 'request_lines', 'saved_versions', 'locked_studies',
        'tender_overrides', 'award_group_configurations', 'award_groups',
        'award_group_memberships', 'user_app_permissions', 'app_audit_log',
        'mo_suppliers', 'mo_receivers', 'mo_contracts', 'mo_contract_items',
        'mo_orders', 'mo_order_items'
      ])
  loop
    execute format('drop policy %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end;
$$;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'profiles', 'municipal_units', 'procurement_groups', 'materials',
    'unit_requests', 'request_lines', 'saved_versions', 'locked_studies',
    'tender_overrides', 'award_group_configurations', 'award_groups',
    'award_group_memberships', 'user_app_permissions', 'app_audit_log',
    'mo_suppliers', 'mo_receivers', 'mo_contracts', 'mo_contract_items',
    'mo_orders', 'mo_order_items'
  ]
  loop
    execute format('alter table public.%I enable row level security', v_table);
    execute format('revoke all on table public.%I from anon, authenticated', v_table);
  end loop;
end;
$$;

grant select on public.profiles to authenticated;
create policy profiles_select_scoped on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.app_is_admin());

grant select on public.municipal_units, public.procurement_groups, public.materials to authenticated;
create policy municipal_units_select_authenticated on public.municipal_units
  for select to authenticated using (auth.uid() is not null);
create policy procurement_groups_select_authenticated on public.procurement_groups
  for select to authenticated using (auth.uid() is not null);
create policy materials_select_authenticated on public.materials
  for select to authenticated using (auth.uid() is not null);

grant insert, update, delete on public.materials to authenticated;
create policy materials_insert_admin on public.materials
  for insert to authenticated with check (public.app_is_admin());
create policy materials_update_admin on public.materials
  for update to authenticated using (public.app_is_admin()) with check (public.app_is_admin());
create policy materials_delete_admin on public.materials
  for delete to authenticated using (public.app_is_admin());

grant select on public.tender_overrides to authenticated;
grant insert, update, delete on public.tender_overrides to authenticated;
create policy tender_overrides_select_authenticated on public.tender_overrides
  for select to authenticated using (auth.uid() is not null);
create policy tender_overrides_insert_admin on public.tender_overrides
  for insert to authenticated with check (public.app_is_admin());
create policy tender_overrides_update_admin on public.tender_overrides
  for update to authenticated using (public.app_is_admin()) with check (public.app_is_admin());
create policy tender_overrides_delete_admin on public.tender_overrides
  for delete to authenticated using (public.app_is_admin());

grant select on public.unit_requests to authenticated;
create policy unit_requests_select_scoped on public.unit_requests
  for select to authenticated
  using (public.app_can_read_unit(municipal_unit_id::bigint));

grant select on public.request_lines to authenticated;
create policy request_lines_select_scoped on public.request_lines
  for select to authenticated
  using (
    exists (
      select 1 from public.unit_requests r
      where r.id = request_lines.request_id
        and public.app_can_read_unit(r.municipal_unit_id::bigint)
    )
  );

grant select on public.saved_versions to authenticated;
create policy saved_versions_select_scoped on public.saved_versions
  for select to authenticated
  using (
    exists (
      select 1 from public.unit_requests r
      where r.id = saved_versions.request_id
        and public.app_can_read_unit(r.municipal_unit_id::bigint)
    )
  );

grant select on public.locked_studies to authenticated;
create policy locked_studies_select_scoped on public.locked_studies
  for select to authenticated
  using (public.app_can_read_unit(municipal_unit_id::bigint));

grant select on public.award_group_configurations, public.award_groups,
  public.award_group_memberships to authenticated;
create policy award_group_configurations_select_authenticated on public.award_group_configurations
  for select to authenticated using (auth.uid() is not null);
create policy award_groups_select_authenticated on public.award_groups
  for select to authenticated using (auth.uid() is not null);
create policy award_group_memberships_select_authenticated on public.award_group_memberships
  for select to authenticated using (auth.uid() is not null);

grant select on public.user_app_permissions to authenticated;
create policy user_app_permissions_select_scoped on public.user_app_permissions
  for select to authenticated
  using (user_id = auth.uid() or public.app_is_admin());

grant select on public.app_audit_log to authenticated;
create policy app_audit_log_select_scoped on public.app_audit_log
  for select to authenticated
  using (
    public.app_can_supervise()
    or actor_user_id = auth.uid()
  );

alter table public.mo_suppliers alter column created_by set default auth.uid();
alter table public.mo_receivers alter column created_by set default auth.uid();

grant select, insert, update, delete on public.mo_suppliers, public.mo_receivers to authenticated;
create policy mo_suppliers_select_authenticated on public.mo_suppliers
  for select to authenticated using (auth.uid() is not null);
create policy mo_suppliers_insert_writer on public.mo_suppliers
  for insert to authenticated
  with check (
    public.app_current_role() in ('admin', 'unit_user')
    and coalesce(created_by, auth.uid()) = auth.uid()
  );
create policy mo_suppliers_update_owner on public.mo_suppliers
  for update to authenticated
  using (public.app_can_supervise() or created_by = auth.uid())
  with check (public.app_can_supervise() or created_by = auth.uid());
create policy mo_suppliers_delete_owner on public.mo_suppliers
  for delete to authenticated
  using (public.app_can_supervise() or created_by = auth.uid());

create policy mo_receivers_select_authenticated on public.mo_receivers
  for select to authenticated using (auth.uid() is not null);
create policy mo_receivers_insert_writer on public.mo_receivers
  for insert to authenticated
  with check (
    public.app_current_role() in ('admin', 'unit_user')
    and coalesce(created_by, auth.uid()) = auth.uid()
  );
create policy mo_receivers_update_owner on public.mo_receivers
  for update to authenticated
  using (public.app_can_supervise() or created_by = auth.uid())
  with check (public.app_can_supervise() or created_by = auth.uid());
create policy mo_receivers_delete_owner on public.mo_receivers
  for delete to authenticated
  using (public.app_can_supervise() or created_by = auth.uid());

grant select on public.mo_contracts to authenticated;
create policy mo_contracts_select_scoped on public.mo_contracts
  for select to authenticated
  using (public.app_can_read_unit(municipal_unit_id::bigint));

grant select on public.mo_contract_items to authenticated;
create policy mo_contract_items_select_scoped on public.mo_contract_items
  for select to authenticated
  using (
    exists (
      select 1 from public.mo_contracts c
      where c.id = mo_contract_items.contract_id
        and public.app_can_read_unit(c.municipal_unit_id::bigint)
    )
  );

grant select on public.mo_orders to authenticated;
create policy mo_orders_select_scoped on public.mo_orders
  for select to authenticated
  using (public.app_can_read_unit(municipal_unit_id::bigint));

grant select on public.mo_order_items to authenticated;
create policy mo_order_items_select_scoped on public.mo_order_items
  for select to authenticated
  using (
    exists (
      select 1 from public.mo_orders o
      where o.id = mo_order_items.order_id
        and public.app_can_read_unit(o.municipal_unit_id::bigint)
    )
  );

create or replace function public.admin_set_app_permissions(
  p_user_id uuid,
  p_can_supervise boolean
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_before jsonb;
  v_after jsonb;
begin
  if not public.app_is_admin() then
    raise exception using errcode = '42501', message = 'Μόνο διαχειριστής μπορεί να μεταβάλει δικαιώματα εφαρμογής.';
  end if;
  if not exists (select 1 from public.profiles p where p.id = p_user_id) then
    raise exception 'Δεν βρέθηκε προφίλ για τον επιλεγμένο χρήστη.';
  end if;

  select to_jsonb(p) into v_before
  from public.user_app_permissions p
  where p.user_id = p_user_id;

  insert into public.user_app_permissions (user_id, can_supervise, updated_at, updated_by)
  values (p_user_id, coalesce(p_can_supervise, false), now(), auth.uid())
  on conflict (user_id) do update
    set can_supervise = excluded.can_supervise,
        updated_at = now(),
        updated_by = auth.uid();

  select to_jsonb(p) into v_after
  from public.user_app_permissions p
  where p.user_id = p_user_id;

  perform public.app_write_audit(
    'permissions_changed', 'user_app_permissions', p_user_id::text, null,
    'Μεταβολή ρητού δικαιώματος εποπτείας', v_before, v_after, '{}'::jsonb
  );
  return true;
end;
$$;

revoke all on function public.admin_set_app_permissions(uuid,boolean) from public, anon;
grant execute on function public.admin_set_app_permissions(uuid,boolean) to authenticated;

revoke all on function public.app_current_role() from public, anon;
revoke all on function public.app_current_unit_id() from public, anon;
revoke all on function public.app_is_admin() from public, anon;
revoke all on function public.app_can_supervise() from public, anon;
revoke all on function public.app_can_read_unit(bigint) from public, anon;
revoke all on function public.app_can_write_unit(bigint) from public, anon;
grant execute on function public.app_current_role() to authenticated;
grant execute on function public.app_current_unit_id() to authenticated;
grant execute on function public.app_is_admin() to authenticated;
grant execute on function public.app_can_supervise() to authenticated;
grant execute on function public.app_can_read_unit(bigint) to authenticated;
grant execute on function public.app_can_write_unit(bigint) to authenticated;

comment on table public.user_app_permissions is
  'Ρητά δικαιώματα εφαρμογής. Δεν χρησιμοποιούνται email ως μηχανισμός εξουσιοδότησης.';
comment on table public.app_audit_log is
  'Αμετάβλητο ίχνος κρίσιμων ενεργειών της εφαρμογής v36.2.';
comment on column public.locked_studies.record_status is
  'Η ακύρωση διατηρεί τη μελέτη στο ιστορικό· δεν επιτρέπεται hard delete.';

commit;
